### ISSUE TITLE
config-reloader does not successfully reload after `global scrape timeout greater than scrape interval` failure 

### ISSUE THREAD

**Issue by SuperMatt** [prometheus-operator/prometheus-operator#4705]
**What happened?**

When a user accidentally changed their global scrape timeout variable to be larger than the global scrape interval, the prometheus instance rightfully asserted that it could not reload the config. A fix was put in place to revert the change and the new config was rolled out. However, the config reloader did not successfully reload the new config, and instead reported the following:

```{"caller":"reloader.go:362","err":"trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?","level":"error","msg":"Failed to trigger reload. Retrying.","ts":"2022-03-30T20:36:09.395322386Z"}```

Note: web.enable-lifecycle is enabled.

After this, there were no attempts to trigger a reload, and as a result the prometheus instance was reporting metrics that the last reload was unsuccessful, despite a correct configuration.

**Did you expect to see something different?**

I expected to see a successful configuration reload

**How to reproduce it (as minimally and precisely as possible)**:

- modify the global scrapeTimeout so that it is larger than the scrapeInterval
- apply changes
- check prometheus logs to show that it cannot reload the configuration
- revert the change so that the scrapeTimeout so that it is smaller than the scrapeInterval again
- watch the config-reloader logs

After a few minutes you will see that the reload is not successful, but it will not trigger any more reload attempts. If you also watch the prometheus logs, you will see no more attempts are made. Finally, check the prometheus metrics and status page, and you'll see that the last reload was unsuccessful.

**Environment**

* Prometheus Operator version: 0.49.0

* Kubernetes version information: 1.21.5

* Kubernetes cluster kind: eks

**Anything else we need to know?**:

I have performed a test in which I manually caused the reload of the configuration using a curl command, and this works successfully, so it is not prometheus itself at fault. Instead it has to be the config-reloader causing the issues.

**Comment by slashpai** [comment]
The issue with scrapeTimeout set larger than scrapeInterval was fixed in `0.54.1`, can you try with that version?

**Comment by simonpasquier** [comment]
I tried to reproduce and indeed it looks like the config reloader can't recover even after you fix the bad configuration.

*How to reproduce*

* Deploy a Prometheus object with 2 replicas and wait for the replicas to be ready.
* Edit the Prometheus object to trigger an invalid configuration (e.g. `spec.queryLogFile: tmp/query.log`)
* Watch the config reloader logs and wait to see errors.
* Revert the changes to the Prometheus object.

I'd expect the reloader to reload Prometheus with the good configuration but instead it stops doing anything.

Logs:
```
level=error ts=2022-04-04T12:42:55.379011742Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:00.373310041Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:05.377459791Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:10.376687695Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:15.386690876Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:20.380568484Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:25.385406333Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:30.384269587Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:35.376230515Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:40.396371017Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:45.375128759Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2022-04-04T12:43:50.370402327Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://localhost:9090/-/reload\": context deadline exceeded"
level=error ts=2022-04-04T12:43:50.37050166Z caller=reloader.go:382 msg="Failed to trigger reload. Retrying." err="trigger reload: reload request failed: Post \"http://localhost:9090/-/reload\": context deadline exceeded"
```

And the logs stop there. The `context deadline exceeded` message is suspicious but coincides with the good configuration being being recovered.

**Comment by SuperMatt** [comment]
I've just tried with v0.55.1 but the bug is still present. The result is exactly the same as before, and the same as the comment above from @simonpasquier. The logs stop and Prometheus still considers the last reload to be unsuccessful.

**Comment by majidrajabi** [comment]
Same issue. Have you any progress @SuperMatt ?

**Comment by SuperMatt** [comment]
I'm not a developer on the project, so I wouldn't know where to start with fixing this issue. We have managed to protect ourselves against this bug by putting in tests in our CI/CD which fail if the scrape_timeout is larger than the scrape_interval, but it does not fix the bug.

**Comment by majidrajabi** [comment]
Above you said that you manually reload the configuration with curl. Can you please share that curl command?

**Comment by SuperMatt** [comment]
@majidrajabi much like this, though note that the url will be different for you.
```curl -X PUT http://prometheus.url:9090/-/reload```

**Comment by slashpai** [comment]
@SuperMatt Does version `v0.54.1` let you define ScrapeTimeout greater than ScrapeInterval? 
It should reject the config and report the error in prometheus-operator log

**Comment by SuperMatt** [comment]
I had only previously tested the config reloader itself. I will test the actual prometheus operator now, to see if it blocks the change.

**Comment by SuperMatt** [comment]
Can confirm that the operator blocks the config with the following message:
```level=info ts=2022-04-07T12:51:01.459854704Z caller=operator.go:1228 component=prometheusoperator key=foobar msg="sync prometheus" level=error ts=2022-04-07T12:51:01.701282741Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"foobar\" failed: creating config failed: generating config failed: scrapeTimeout \"10s\" greater than scrapeInterval \"5s\""
```

**Comment by simonpasquier** [comment]
FWIW I've filed https://github.com/prometheus-operator/prometheus-operator/issues/4708 to investigate why the reloader doesn't reload the Prometheus configuration after it got fixed.
